### ISSUE TITLE
Longer property names cause misalignment in Property Details

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#446]
Current Behaviour: In cases where the name is longer and doesn't fit in one line, the component with the property info in Property Details becomes longer than the photo component. 

Example: https://landworks.xyz/property/62
![Screenshot 2022-04-06 at 9.28.10.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/3bf8020f-2083-428b-9a82-54419d59d59e)

Expected new behaviour: Both components need to be the same hight. When this happens we want the photo component to be the same hight and to be scaled proportionally.

**Comment by xdemocle** [comment]
@StilyanMitrev I hope you gave this shitty bug to me because confident in my skills not as punishment :D

**Comment by xdemocle** [comment]
so, maximum I can do is the below screenshots. Unfortunately I can't make dynamic the size of left box because is actually the one that decide the fixed height of the two column blocks. 

So, I put the title on one line cut with ellipsis and when you over it you can see the full title.

With long title:
![Screen Shot 2022-04-07 at 7.27.11 PM.png](https://images.zenhubusercontent.com/61f9049296919137cb9fbade/1e9756af-0b4a-4ac4-995f-70a8beb13474)

With normal size title:
![Screen Shot 2022-04-07 at 7.27.20 PM.png](https://images.zenhubusercontent.com/61f9049296919137cb9fbade/29a0409e-0046-4abc-90f5-d7f8fc054837)

**Comment by StilyanMitrev** [comment]
to be tested on prod
