### ISSUE TITLE
Browse land for sale within the listing process

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#969]
Story: As a PO, I’d like users to be able to browse land for sale directly from LandWorks in order to increase number of listed properties.

1.	Once the user clicks the BUY LAND button from #XXX then land NFTs for sale should be displayed. The data for the listed NFTs should come from OpenSea because there is little to no volume for the collections we are interested in on other marketplaces.
2.	The land NFTs for sale should look the same way as the card components we have in the listing process so we should reuse the component we have in the listing process. The differences in the component are:
- In the last row of the component, we should have the price the cryptocurrency it’s listed and in $ next to it [as per design](https://www.figma.com/file/2b3IsJsAD3Pi4S9wwKD1zZ/Stilyan-LandWorks?node-id=771%3A1264&t=OHUjV1HeZRKulZsu-4).  There might be various currencies but that should be resolved by the API call. 
- If both prices (in crypto and in $) do not fit in the card component, hide the $ value as the crypto value is mor important. 
- In the right corner of the card component there should be an OpenSea icon to indicate that the listing is from OpenSea. Make sure the icon is clickable with a tooltip that says “View on OpenSea”. If the user clicks it – open the item in a new tab. If the user clicks anywhere else in the card it should indicate a selection of the card.
- Load 32 NFTs on load (4 full scrolls) in order to limit the calls. Load 32 more once the user reaches to the bottom.
3.	When the user is browsing NFTs we should have an extra component in Step 1 alongside the Metaverse selector and the type dropdown. The additional component should be a sort. 
- By default, the selection should be “Price: lowest first”.
- The only other available sorting options should be Price: highest first

**Comment by failfmi** [comment]
The idea is to integrate buying for Decentraland NFTs (both LAND and Estate) from OpenSea (https://opensea.io/collection/decentraland/). This means that we want to be able to buy and list the NFT in LandWorks in one transaction.

We will integrate Reservoir’s API (https://reservoir.tools/), the docs is: https://docs.reservoir.tools/docs/reservoir-api
* Create an env variable called `REACT_APP_RESERVOIR_API_URL`, which will have https://api.reservoir.tools/ for `prod`, and https://api-goerli.reservoir.tools/ for `dev`

For that we will have to interact with two of their endpoints + one contract interaction from us.
* The first endpoint is to fetch all the orders/asks that are found on OpenSea for the DCL collections (use `config.contracts.decentraland` for the collection addresses)
  * API docs: https://docs.reservoir.tools/reference/getordersasksv4
  * Example: https://api-goerli.reservoir.tools/orders/asks/v4?contracts=0x359EE0FD3f452147cC88ADf06d457316a643da32&contracts=0x7a7f6C8a0715fb34E92c31985B98C9EF833044f8&source=opensea.io&sortBy=price
  * Where `contracts` are the decentraland contract addresses from the configuration, fetching only from `opensea` marketplace, and `sorted by price in ascending order`. It would be best to add pagination using `limit` field and optimise it.
  * When you take a look at the result, you will see everything necessary for the LandWorks design view:
    * You will rebuild the image url from `tokenSetId` (it contains contract address and tokenId) - depending on contract address use from FE `getEstateImageUrl` or `getDecentralandDataImageUrl`
    * Create the name based on LAND coordinates or when its estate, fetch its size
    * Coordinates is the same
    * OpenSea logo is found in `source.icon`
    * The price of the NFT is found in `price` ( currency and amount). You will need the raw values for contract interaction and can visualise the decimal/native to the user
* When the user selects an NFT, trigger the usual LandWorks list steps.
  * Do not display the ads step, as the user will not be able to sign the agreement, because he is not the actual owner.
* When the user reaches the last step (Summary), assert that the user has the necessary payment amount in his wallet:
  * Show error messages for the following:
    * If the payment for the NFT is ETH:
      * Check the user’s balance is `>` required payment.
    * If the payment for the NFT is ERC-20:
      * Check the User’s ERC-20 balance of the given token - create an instance, call `balanceOf` and check whether his balance is `>` required payment.
      * Load the user allowance for the buy contract (`config.contracts.buyContract`), call `ERC20.loadAllowance(buyContract)`
* Then it comes the second request:
  * API docs: https://docs.reservoir.tools/reference/postexecutebuyv6
  * Example:
    * POST https://api-goerli.reservoir.tools/execute/buy/v6
    * BODY:
```json
{
    "tokens": [
          "0x7a7f6c8a0715fb34e92c31985b98c9ef833044f8:7"
     ],
     "onlyPath": false,
     "normalizeRoyalties": false,
     "partial": false,
     "skipBalanceCheck": true,
     "source": "opensea.io",
     "taker": "0x0f2F6623aC4b94e1d61B4Cd195A6c28992310F96"
}
```
  * The request above fetches the buy details for NFT with contract address `0x7a7f6c8a0715fb34e92c31985b98c9ef833044f8`, token id `7`, that you want to buy it from opensea and that the buyer/taker is `0x0f2F6623aC4b94e1d61B4Cd195A6c28992310F96` (here use `wallet.address` from `useWallet()`) Skip the balance check using `skipBalanceCheck` otherwise it might revert if the user does not have the payment in the wallet.
  * This will return an object with two objects: `steps` and `path`
We need the data from the second step, specifically the step with `id`== `sale` and get the `items[0].[data.to]` and `items[0].data.data`
    * Example:
```json
"to": "0x00000000006c3852cbef3e08e8df289169ede581",
"data": "0xfb0f3ee100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b4c777833380000000000000000000000000000f2f6623ac4b94e1d61b4cd195a6c28992310f9600000000000000000000000000000000000000000000000000000000000000000000000000000000000000007a7f6c8a0715fb34e92c31985b98c9ef833044f80000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000063c021410000000000000000000000000000000000000000000000000000000063e8ffc10000000000000000000000000000000000000000000000000000000000000000360c6ebe00000000000000000000000000000000000000005f076010c25b3c540000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000011c37937e080000000000000000000000000000000a26b00c1f0df003000390027140000faa7190000000000000000000000000000000000000000000000000000000000000041629e50499034dad7220e1d57099aa568b622b6bd0dd7d01de9890feff33e490844e213292f887abe9c8a2774dcfda55e9984dd7b3cfe4d3606294589c3eaaca41c00000000000000000000000000000000000000000000000000000000000000360c6ebe"
```
* Before the actual execution, if the nft payment is ERC-20:
If the allowance is not enough, enable `Approve` button, disable `Buy` and execute `approveAmount(paymentAmount, buyContract)`
* Last, but not least, the actual buy transaction:
  * https://github.com/EnterDAO/LandWorks-FE/tree/feat/buy/contract - Here is the branch with the actual contract interaction
  * set `REACT_APP_CONTRACT_BUY_ADDR` = 0xf5b8f6348922EE9D367Fd1963b80D4d5281b5cdB
  * Create instance of BuyDCLContract and execute `buyETH` or `buyERC20` , depending on the NFT payment
  * Examples:
    * ETH
```typescript
const buyDCLContract = new BuyDCLContract(config.contracts.buyContract);

      buyDCLContract.setProvider(wallet.provider);
      buyDCLContract.setAccount(wallet.account);

      const txReceipt = await buyDCLContract.buyETH(
        {
          metaverseId: selectedMetaverse,
          metaverseRegistry: metaverseRegistry,
          metaverseAssetId: metaverseAssetId,
          minPeriod: minPeriod.toString(),
          maxPeriod: maxPeriod.toString(),
          maxFutureTime: maxFutureTime.toString(),
          paymentToken: paymentToken.id,
          pricePerSecond: pricePerSecond.toFixed(0),
          referrer: DEFAULT_ADDRESS,
        },
        new BigNumber('200000000000000'), // NFT ETH Payment price
        '0x00000000006c3852cbef3e08e8df289169ede581', // Result from steps[1].items[0].to
        '0xfb0f3ee10000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b159f9bb30000000000000000000000000001a22cf1ad6b5bb146664081d495ed576d207c0a20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000359ee0fd3f452147cc88adf06d457316a643da320000000000000000000000000000001200000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000063c013130000000000000000000000000000000000000000000000000000000063e8f1930000000000000000000000000000000000000000000000000000000000000000360c6ebe00000000000000000000000000000000000000006002de4ba17492780000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000048c273950000000000000000000000000000000a26b00c1f0df003000390027140000faa7190000000000000000000000000000000000000000000000000000000000000041224d1b3f6e6937b781e1c4be48f63d6e010e7caf07c50f3a8f9a286af12e11f30d112e9cb4e6f08a0eb560285cafa4049c02a06427670e248ba3066b2a26fa571c00000000000000000000000000000000000000000000000000000000000000360c6ebe'
      );
```

```typescript
const txReceipt = await buyDCLContract.buyERC20(
        {
          metaverseId: selectedMetaverse,
          metaverseRegistry: metaverseRegistry,
          metaverseAssetId: metaverseAssetId,
          minPeriod: minPeriod.toString(),
          maxPeriod: maxPeriod.toString(),
          maxFutureTime: maxFutureTime.toString(),
          paymentToken: paymentToken.id,
          pricePerSecond: pricePerSecond.toFixed(0),
          referrer: DEFAULT_ADDRESS,
        },
        '0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6', // NFT ERC-20 payment address
        new BigNumber('3000000000000000'), // NFT payment amount
        '0x00000000006c3852cbef3e08e8df289169ede581', // Result from steps[1].items[0].to
        '0xfb0f3ee10000000000000000000000000000000000000000000000000000000000000020000000000000000000000000b4fbf271143f4fbf7b91a5ded31805e42b2208d60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a6445a1f7d0000000000000000000000000001a22cf1ad6b5bb146664081d495ed576d207c0a20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000359ee0fd3f452147cc88adf06d457316a643da320000000000000000000000000000001400000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000063c01e080000000000000000000000000000000000000000000000000000000063e8fc880000000000000000000000000000000000000000000000000000000000000000360c6ebe0000000000000000000000000000000000000000e10efd2cc33a552a0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000044364c5bb0000000000000000000000000000000a26b00c1f0df003000390027140000faa7190000000000000000000000000000000000000000000000000000000000000041788ba6cfb853b63bb37f8ce0b7d85424816cb1d9937b77efb0196599a75844a80165ae3465835d94432fa3f9152def471640ec9de46ea39b7822fd30b0ed81781b00000000000000000000000000000000000000000000000000000000000000360c6ebe'
      );
 ```
